# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myfunctionA <- function(x) {
    .Call(`_Question2_myfunctionA`, x)
}

myfunctionB <- function(x) {
    .Call(`_Question2_myfunctionB`, x)
}

